### ISSUE TITLE
How to Compile ExtraNet

### ISSUE THREAD

**Issue by jiayaozhang** [fuxihao66/ExtraNet#2]
`In UE425ExtraNet_Active/Engine/Source/Runtime/Renderer/Private/PostProcess`

I didn't find `MotionVectorAndUSedCount.cpp and MotionVectorAndUSedCount.h`

BaseEngine.ini from `https://github.com/fuxihao66/UnrealEngine/tree/UE425ExtraNet_active` 

I didin't find `MotionVector=(Material="/Engine/BufferVisualization/MotionVector.MotionVector", Name=LOCTEXT("MotionVector", "MotionVector"))
` 

But the links from ` https://drive.google.com/drive/folders/1ZUbct6Z2T3gGhbxjQU0-u2PPflwYv-UZ?usp=sharing` contains it.

Also I have tried the `EngineModificationGuide`, but the higher version of UE, for example UE 5.1 ,

would get different errors, since the higher version of UE don't have `RenderGraphBarrierBatcher.cpp` for example

So which is the right link to follow and implement the ExtraNet in order to get the raw data?

Many Thanks!

**Comment by fuxihao66** [comment]
I add the required modification to UE5.1: https://github.com/fuxihao66/UnrealEngine/tree/5.1.
You can clone this branch, run Steup and Generate, and then copy all of the uasset files in https://github.com/fuxihao66/ExtraNet/tree/main/EngineModificationGuide/BufferVisualization to replace the original ones.

(These uasset files will be regenerated whenever you run GenerateProjectFiles.bat, so you need to copy these files **after** generating projects.)

**Comment by Marm7** [comment]
I found that the link for UE5.1 https://github.com/fuxihao66/UnrealEngine/tree/5.1 cannot be downloaded anymore. Could you please provide me with the link to reproduce it? Thank you!

**Comment by fuxihao66** [comment]
> I found that the link for UE5.1 https://github.com/fuxihao66/UnrealEngine/tree/5.1 cannot be downloaded anymore. Could you please provide me with the link to reproduce it? Thank you!

You need to follow this [instruction ](https://www.unrealengine.com/en-US/ue-on-github) to see the repo.
