### ISSUE TITLE
Modified UE5

### ISSUE THREAD

**Issue by Sodiride123** [fuxihao66/ExtraNet#5]
I want to use the modified UE you mentioned to generate the raw data. I found the https://github.com/fuxihao66/UnrealEngine/tree/5.1 is no longer available. Could you please provide a copy of the modified UE5?

**Comment by fuxihao66** [comment]
Did you follow the instructions of [accessing UE Official Repo](https://www.unrealengine.com/en-US/ue-on-github)?
