### ISSUE TITLE
About the demodulation part

### ISSUE THREAD

**Issue by Sodiride123** [fuxihao66/ExtraNet#6]
Hi, fuxihao66

Thanks for providing me the guidance for the previous question. 
I saw you obtained Actual shading frame before tone mapping (PreTonemapHDRColor) and albedo (Base color) for demodulation in your paper. Can I just use the Actual shading frame AFTER tone mapping and albedo for demodulation, which means I use the final rendered image to divide by albedo to get the irradiance?

**Comment by fuxihao66** [comment]
I do not recommend doing demodulation after tonemapping. Because the color buffer after tonemapping is mapped **non-linearly** to [0,1] srgb color space. You should do demodulation in linear color space to get irradiance image.

**Comment by Sodiride123** [comment]
Thanks for your reply. Regarding the demodulation, for the general scene(may not involve many glossy materials), will there be a significant difference in the final results between using base color and using BRDF demodulation?

**Comment by fuxihao66** [comment]
Using base color for demodulation should be fine for diffuse materials.
