### ISSUE TITLE
About Occlusion Motion Vector

### ISSUE THREAD

**Issue by JHex-git** [fuxihao66/ExtraNet#7]
Hello, I have recently read your paper and I'm struggling to implement occlusion motion vectors mentioned in it as I am not familiar with UE source code. I know occlusion motion vectors is the work of 《Temporally Reliable Motion Vectors for Real-time Ray Tracing》 but I fail to find the source code for reference. So could you please also share your implementation of this if possible?  If not, any guidance or tips are also highly appreciated. 
In the formula $z = P_iT(y)P_{i-1}^{-1}y$, $T(y)$ is the forward velocity, which accept previous coordinate as input, but UE only renders backward velocity, which accept current coordinate as input. If I want to get forward velocity, I have to add extra render texture, write a similar shader like VelocityShader.usf, modify the output Position of vertex shader and add atomic write in the pixel shader according to depth. But as velocity is 3d(takes four channel, no place for depth), atomic write cannot be simply tackled using `InterlockedMin`.

**Comment by fuxihao66** [comment]
I have added the implementation to the "OcclusionMV" folder.

**Comment by JHex-git** [comment]
> I have added the implementation to the "OcclusionMV" folder.

Thank you so much for your help!

**Comment by fuxihao66** [comment]
> But as velocity is 3d(takes four channel, no place for depth), atomic write cannot be simply tackled using InterlockedMin

By the way, the **velocity** used in UE is actually not the motion vector we used. Velocity is defined on NDC space, and accounting only object movement, while motion vector is defined on UV space, consisting of object movement and camera movement. We compute [motion vector based on velocity](https://github.com/fuxihao66/UnrealEngine/blob/5.1/Engine/Shaders/Private/MotionVectorAndCountUsed.usf) and only x and y components are used (so you can pack motion vector and depth to a 64bit variable).
